src/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from levels import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('students/', include('students.urls')),
    path('class/', include('levels.urls')),
    path('course/', include('courses.urls')),

    path('', views.levels_get),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('add/', views.student_add, name='student-add'),
    path('update/<int:student_id>/', views.student_update, name='student-update'),
    path('del/<int:student_id>/<int:class_id>/', views.student_delete, name='student-delete'),
    path('profile/<int:student_id>', views.profile, name='student-profile'),
    path('all/<int:class_id>/<int:course_id>', views.students_get, name='students-list'),
    path('mark/', views.mark_attendance_manually, name="student-attendance-mark"),
    path('mark/auto/', views.mark_attendance_automatically, name="student-attendance-mark-automatically"),

    path('email/', views.email_warning, name="email-service"),
    path('stats/<int:course_id>/<int:class_id>/<int:teacher_id>', views.stats, name='students-stats'),
    path('stats/details/<int:detail_id>', views.stats_details, name="students-stats-details")
]

students/models.py
from django.db import models
from authentication.models import UserProfile
from levels.models import Class_uni
from courses.models import Course


# Create your models here.
class Student(models.Model):
    cin = models.IntegerField()
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    phone = models.IntegerField(null=False, default="711111111")
    email = models.CharField(max_length=255, default="student@mail.com")
    profile_pic = models.ImageField(default="no_image.png", null=False, blank=False)

    class_id = models.ForeignKey(Class_uni, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.first_name


class Attendance_image(models.Model):
    teacher = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    classe = models.ForeignKey(Class_uni, on_delete=models.CASCADE)
    nb_p = models.IntegerField(null=False)

    attendance_pic = models.ImageField(default="no_image.png", null=False, blank=False, upload_to='attendance')

    date = models.DateTimeField(auto_now_add=True, blank=True)


class Attendance_detail(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    classe = models.ForeignKey(Class_uni, on_delete=models.CASCADE)

    present = models.BooleanField(default=True)
    date = models.DateField(auto_now_add=True, blank=True)


class Elimination(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    nb_absences = models.IntegerField()
    eliminated = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True, blank=True)

students/forms.py
from django.forms import ModelForm
from students.models import Student
from students.models import Attendance_detail
from levels.models import Class_uni
from django import forms


class StudentForm(ModelForm):
    first_name = forms.CharField(label='First name',
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Last name',
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    cin = forms.IntegerField(label='CIN',
                             widget=forms.NumberInput(attrs={'class': 'form-control'}))
    date_of_birth = forms.DateField(label='Date of birth',
                                    widget=forms.SelectDateWidget(
                                        attrs={'class': 'form-control date'}))
    email = forms.CharField(label='Email',
                            widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone = forms.IntegerField(label='Phone',
                               widget=forms.NumberInput(attrs={'class': 'form-control'}))
    profile_pic = forms.ImageField(label='Profile picture',
                                   widget=forms.FileInput(attrs={'class': 'form-control'}))

    class_id = forms.ModelChoiceField(queryset=Class_uni.objects.filter(), required=True,
                                      widget=forms.Select(attrs={'class': 'form-control c'}))

    class Meta:
        model = Student
        exclude = ()

students/views.py
from datetime import datetime
from random import randint

from django.shortcuts import render, redirect
from django.urls import reverse

from authentication.models import UserProfile
from courses.models import Course
from students.forms import StudentForm
from students.models import Student, Attendance_detail, Elimination, Attendance_image
from django.contrib import messages

from levels.models import Class_uni
from django.utils import timezone
from students.filters import StudentFilter

from django.core.mail import send_mail
from django.conf import settings

import face_recognition
from PIL import Image, ImageDraw
from django.utils.crypto import get_random_string


# Create your views here.

def email_warning(request, email, course_id):
    course = Course.objects.get(id=course_id)
    course_name = course.name

    subject = 'Elimination warning !'
    message = 'Dear student, please beware because you are running out of permitted absences number for ' + course_name
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [
        email,
    ]
    send_mail(subject, message, email_from, recipient_list)
    return render(request, '../templates/student_add.html')


def student_add(request):
    student = Student()
    form = StudentForm()

    if request.method == 'POST':
        form = StudentForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            messages.success(request, 'Student successfully added')
            return redirect(reverse('students:student-add'))

    context = {
        'form': form
    }
    return render(request, '../templates/student_add.html', context)


def students_get(request, class_id, course_id):
    students = Student.objects.filter(class_id=class_id)
    classe = Class_uni.objects.get(id=class_id)

    my_filter = StudentFilter(request.GET, queryset=students)
    students = my_filter.qs

    test = False

    today = timezone.datetime.today()
    attendance_today = Attendance_detail.objects.filter(date=today, course_id=course_id, classe_id=class_id)

    nb = attendance_today.count()

    if nb is not 0:
        test = True
        presents = 0

        for p in attendance_today:
            if p.present is True:
                presents = presents + 1

        pourcentage = round((presents / nb) * 100, 2)

        context = {
            "filter": my_filter,
            "students": students,
            "classe": classe,
            "classid": class_id,
            "courseid": course_id,
            "presents": presents,
            "pourcentage": pourcentage,
            'test': test
        }
        return render(request, '../templates/students_list.html', context)

    context = {
        "filter": my_filter,
        "students": students,
        "classe": classe,
        "classid": class_id,
        "courseid": course_id,
        'test': test
    }

    return render(request, '../templates/students_list.html', context)


def profile(request, student_id):
    queryset = Student.objects.get(id=student_id)
    context = {
        "student": queryset
    }
    return render(request, '../templates/student_profile.html', context)


def student_delete(request, student_id, class_id):
    student = Student.objects.get(id=student_id)
    student.delete()
    messages.success(request, 'Student successfully deleted')

    return redirect(reverse('levelss:level-details', kwargs={'class_id': class_id}))


def student_update(request, student_id):
    student = Student.objects.get(id=student_id)
    class_id = student.class_id

    form = StudentForm(request.POST or None, request.FILES, instance=student)

    if request.method == 'POST':
        form = StudentForm(request.POST or None, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            messages.success(request, 'Student successfully updated')
            return redirect(reverse('students:student-add'))
    else:
        form = StudentForm()

    is_update = True

    context = {
        'student': student,
        'class': class_id,
        'form': form,
        'is_update': is_update
    }

    return render(request, '../templates/student_update.html', context)


def mark_attendance_manually(request):

    if request.method == 'POST':
        present_students_ids = request.POST.getlist('p')

        course_id = request.POST.get('course_id')
        course = Course.objects.get(id=course_id)

        course_nb_absences = course.absences_number

        class_id = request.POST.get('class_id')
        classe = Class_uni.objects.get(id=class_id)
        all_students = Student.objects.filter(class_id=class_id)

        all_students_ids = []

        for s in all_students:
            all_students_ids.append(s.id)

        absent_students_ids = list(set(all_students_ids) - set(map(int, present_students_ids)))

        for student_id in present_students_ids:

            student = Student.objects.get(id=student_id)
            attendance_sheet = Attendance_detail(student=student, course=course, present=True, date=datetime.now,
                                                 classe=classe)
            attendance_sheet.save()

            elimination_sheet = Elimination.objects.filter(student_id=student.id).last()

            if elimination_sheet:
                nb_absences = elimination_sheet.nb_absences

                if course_nb_absences - elimination_sheet.nb_absences <= 0:
                    is_eliminated = True

                    elimination_sheet.student = student
                    elimination_sheet.course = course
                    elimination_sheet.eliminated = is_eliminated
                    elimination_sheet.nb_absences = nb_absences
                    elimination_sheet.date = timezone.now()

                    elimination_sheet.save()

            elif elimination_sheet is None:
                elimination_sheet = Elimination(student=student, course=course, eliminated=False,
                                                nb_absences=0)
                elimination_sheet.save()

        for student_id in absent_students_ids:
            student = Student.objects.get(id=student_id)

            attendance_sheet = Attendance_detail(student=student, course=course, present=False, date=datetime.now,
                                                 classe=classe)
            attendance_sheet.save()

            elimination_sheet = Elimination.objects.filter(student_id=student.id).last()

            if elimination_sheet:
                nb_absences = elimination_sheet.nb_absences + 1

                if course_nb_absences - elimination_sheet.nb_absences <= 0:
                    is_eliminated = True

                    elimination_sheet.student = student
                    elimination_sheet.course = course
                    elimination_sheet.eliminated = is_eliminated
                    elimination_sheet.nb_absences = nb_absences
                    elimination_sheet.date = timezone.now()

                    elimination_sheet.save()
                else:
                    elimination_sheet.student = student
                    elimination_sheet.course = course
                    elimination_sheet.nb_absences = nb_absences
                    elimination_sheet.date = timezone.now()

                    elimination_sheet.save()

                    if course_nb_absences - nb_absences == 1:
                        email_warning(request, student.email, course_id)

            elif elimination_sheet is None:
                elimination_sheet = Elimination(student=student, course=course, eliminated=False,
                                                nb_absences=1, date=timezone.now())
                elimination_sheet.save()

    messages.success(request, 'Student successfully marked')
    return redirect(reverse('students:students-list', kwargs={'class_id': class_id, 'course_id': course_id}), )


def mark_attendance_automatically(request):
    if request.method == 'POST':

        course_id = request.POST.get('course_id')
        class_id = request.POST.get('class_id')
        teacher_id = request.POST.get('teacher_id')
        attendance_pic = request.FILES.get('pic')

        course = Course.objects.get(id=course_id)
        classe = Class_uni.objects.get(id=class_id)
        teacher = UserProfile.objects.get(user_id=teacher_id)

        course_nb_absences = course.absences_number

        all_students = Student.objects.filter(class_id=class_id)

        students_encodings = []
        students_names = []
        all_students_ids = []
        present_students_idss = []

        for s in all_students:
            pic = str(s.profile_pic)

            url = "static/images/uploads/" + pic

            image_of_student = face_recognition.load_image_file(url)
            student_face_encoding = face_recognition.face_encodings(image_of_student)[0]
            students_encodings.append(student_face_encoding)

            last_name = s.last_name
            first_name = s.first_name
            name = last_name + ' ' + first_name
            students_names.append(name)

            all_students_ids.append(s.id)

        # Load attendance image to find faces in
        attendance_image = face_recognition.load_image_file(attendance_pic)

        # Find faces in attendance image
        face_locations = face_recognition.face_locations(attendance_image)
        face_encodings = face_recognition.face_encodings(attendance_image, face_locations)

        # count faces
        nb_p = len(face_locations)

        # Convert to PIL format
        pil_image = Image.fromarray(attendance_image)

        # Create as ImageDraw instance
        draw = ImageDraw.Draw(pil_image)

        # Loop through faces in test image
        for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
            matches = face_recognition.compare_faces(students_encodings, face_encoding)

students/templates/contact.html
{% extends "base.html" %}

{% block content %}
    hello contact
{% endblock %}

students/templates/students_list.html
{% extends "base.html" %}

{% block content %}
<div class="item-title">
    <h3> {{classe.name}}</h3>
</div>

<div class="row gutters-20">
        <div class="col-xl-3 col-sm-6 col-12">
        <div class="dashboard-summery-one mg-b-20">
            <div class="row align-items-center">
                <div class="col-6">
                    <div class="item-icon bg-light-green ">
                        <i class="flaticon-classmates text-green"></i>
                    </div>
                </div>

                <div class="col-6">
                    <div class="item-content">
                        <div class="item-title">Students</div>
                        <div class="item-number"><span class="counter"> {{students.count}} </span>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        </div>

    <div class="col-3-xxxl col-sm-6 col-12">
                        <div class="dashboard-summery-one">
                            <div class="row">
                                <div class="col-6">
                                    <div class="item-icon bg-light-red">
                                        <i class="flaticon-money text-red"></i>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="item-content">
                                        <a href="{% url 'students:students-stats' course_id=courseid class_id=classid teacher_id=request.user.id %}">

                                        <div class="item-title">Statistics</div>
                                            <div class="item-number"><span>%</span><span class="counter" > {{pourcentage}} </span></div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

</div>

<div class="col-12">
    <div class="card">
        <div class="card height-auto">
            <div class="card-body">
                <form class="mg-b-20">
                    <div class="row gutters-8">

                        <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
                            <input type="number" name="cin" step="any" id="id_cin" placeholder="CIN" class="form-control">
                        </div>
                        <div class="col-4-xxxl col-xl-4 col-lg-3 col-12 form-group">
                            <input type="text" name="last_name" id="id_last_name" class="form-control" placeholder="Last name">
                        </div>
                        <div class="col-4-xxxl col-xl-3 col-lg-3 col-12 form-group">
                            <input type="text" name="first_name" placeholder="First name" class="form-control" id="id_first_name">
                        </div>
                        <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                            <button type="submit" class="btn btn-success">SEARCH</button> <br>
                            <button onClick="window.location.href=window.location.href" class="btn btn-warning" >Reset</button>
                        </div>
                    </div>
                </form>
                <div class="table-responsive">
                    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">
                        <table class="table display data-table text-nowrap dataTable no-footer" id="DataTables_Table_0"
                            role="grid">
                            <thead>
                                <tr role="row">

                                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                        aria-label="Photo: activate to sort column ascending" style="width: 43px;">Photo
                                    </th>
                                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                        aria-label="Name: activate to sort column ascending" style="width: 82px;">Name
                                    </th>
                                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                        aria-label="Phone: activate to sort column ascending" style="width: 101px;">
                                        Phone</th>
                                    <th rowspan="1" colspan="1" aria-label="E-mail: activate to sort column ascending"
                                        style="width: 168px;">E-mail</th>
                                    <th rowspan="1" colspan="1" aria-label="" style="width: 48px;"></th>
                                    {% if courseid != 0 %}
                                        <th rowspan="1" colspan="1" style="width: 87px;">
                                            <div class="form-check">
                                                <label class="form-check-label">Présent</label>
                                                <input type="checkbox" class="form-check-input checkAll">
                                            </div>
                                        </th>
                                    {% endif %}

                                </tr>
                            </thead>
                            <tbody>
                                                            <hr>

                            <form action="{% url 'students:student-attendance-mark-automatically' %}" enctype="multipart/form-data" method="post">
                                    {% csrf_token %}
                                    <input type="file" name="pic" required>
                                    <input type="text" name="course_id" value={{courseid}} hidden>
                                    <input type="text" name="class_id" value={{classe.id}} hidden>
                                    <input type="text" name="teacher_id" value={{request.user.id}} hidden>
                                    <input type="submit" class="btn btn-gradient-yellow" style="    position: relative;
    top: -45px;
    left: 45%;
    height: 35px;
    color: white;
    font-size: 14px;" value="mark presence">
                                <hr>
                            </form>

                            <form action="{% url 'students:student-attendance-mark' %}" method="post">
                                    {% csrf_token %}
                                        {% for student in students %}
                                        <tr role="row" class="odd">
                                            <td class="text-center"><img class="avatar" src="{{student.profile_pic.url}}"
                                                    alt="student">
                                            </td>
                                            <td class="text-left"><a
                                                    href="{% url 'students:student-profile' student_id=student.id %}">
                                                    {{student.last_name}} {{student.first_name}} </a></td>
                                            <td>{{student.phone}}</td>
                                            <td>{{student.email}}</td>
                                            <td>
                                            </td>
                                            {% if courseid != 0 %}
                                                <td class="sorting_1">
                                                    <div class="form-check">
                                                        <input type="checkbox" class="form-check-input" name="p" value={{student.id}}>
                                                        <label class="form-check-label"> </label>
                                                    </div>
                                                </td>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                {% if courseid != 0 %}
                                    <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 float-right form-group">
                                        <input type="text" name="course_id" value={{courseid}} hidden>
                                        <input type="text" name="class_id" value={{classe.id}} hidden>
                                        <input type="submit" class="fw-btn-fill btn-gradient-yellow" value="Mark P"/>
                                    </div>
                                {% endif %}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

students/templates/students_stats.html
{% extends "base.html" %}

{% block content %}


<div class="page-body">

  <div class="row">
    {% for detail in details %}
    <div class="col-sm-6 col-md-6 col-lg-3">
      <div class="team-block">
        <a href="{% url 'students:students-stats-details' detail_id=detail.id %}" class="btn btn-gradient-yellow" style="    margin: 4% 4% 4% 0;
               height: 75px;
               width: 175px;
               color: white;
               font-style: bolder;
               font-size: 15px;"> <span style="position: relative;top: 20px;display: flex;justify-content: center;flex-wrap: wrap;">{{detail.date}}</span> </a>
      </div>
    </div>
    {% endfor %}
    <div>
    </div>
    {% endblock %}

students/templates/students_stats_details.html
{% extends "base.html" %}
<script scr="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js"></script>
{% block content %}

<div class="page-body">

<div class="col-4-xxxl col-xl-6 col-12">
                        <div class="card dashboard-card-three">
                            <div class="card-body">
                                <div class="heading-layout1">
                                    <div class="item-title">
                                        <h3>Attendance Percentage</h3>
                                    </div>

                                </div>
                                <div class="doughnut-chart-wrap"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
    <canvas id="myChart" width="513" height="270"></canvas>
                                </div>
                                <div class="student-report">
                                    <div class="student-count pseudo-bg-blue">
                                        <h4 class="item-title">Absent</h4>
                                        <div class="item-number">{{rest}}%</div>
                                    </div>
                                    <div class="student-count pseudo-bg-yellow">
                                        <h4 class="item-title">Present</h4>
                                        <div class="item-number" id="pourcentage">{{pourcentage}}</div> <div style="    position: relative;
    top: -27px;
    left: 100%;">%</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <div class="table-responsive">
                    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">
                        <table class="table display data-table text-nowrap dataTable no-footer" id="DataTables_Table_0"
                            role="grid">
                            <thead>
                                <tr role="row">

                                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                        aria-label="Photo: activate to sort column ascending" style="width: 43px;">Photo
                                    </th>
                                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                        aria-label="Name: activate to sort column ascending" style="width: 82px;">Name
                                    </th>
                                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                                        aria-label="Phone: activate to sort column ascending" style="width: 101px;">
                                        Phone</th>
                                    <th rowspan="1" colspan="1" aria-label="E-mail: activate to sort column ascending"
                                        style="width: 168px;">E-mail</th>
                                    <th rowspan="1" colspan="1" aria-label="" style="width: 48px;"></th>
                                    {% if courseid != 0 %}
                                        <th rowspan="1" colspan="1" style="width: 87px;">
                                            <div class="form-check">
                                                <label class="form-check-label">Présent</label>
                                                <input type="checkbox" class="form-check-input checkAll">
                                            </div>
                                        </th>
                                    {% endif %}

                                </tr>
                            </thead>
                            <tbody>
                                        {% for student in studentss %}
                                        <tr role="row" class="odd">
                                            <td class="text-center"><img class="avatar" src="{{student.profile_pic.url}}"
                                                    alt="student">
                                            </td>
                                            <td class="text-left"><a
                                                    href="{% url 'students:student-profile' student_id=student.id %}">
                                                    {{student.last_name}} {{student.first_name}} </a></td>
                                            <td>{{student.phone}}</td>
                                            <td>{{student.email}}</td>
                                            <td>
                                            </td>
                                            <td>
                                                    <i class="fas fa-check text-success"></i>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>

                    </div>
                </div>

</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

console.log('here');
var ctx = document.getElementById('myChart').getContext('2d');
var pourcentage = document.getElementById('pourcentage').innerHTML;

var myChart = new Chart(ctx, {
    type: 'doughnut',
    data: {

        labels: ['Presents','Absents'],
        datasets: [{
            data: [pourcentage, 100-pourcentage],
            backgroundColor: [
                'rgba(248, 148, 6, 1)',
                'rgba(37, 116, 169, 1)'
            ],
            borderColor: [
                'rgba(248, 148, 6, 1)',
                'rgba(37, 116, 169, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
    legend: {
        display: false
    }
}
});
</script>
    {% endblock %}