courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('get/', views.course_get_all_teacher, name='course-get'),
    path('get/all', views.course_get_all, name='course-get-all'),
    path('get/<int:class_id>', views.course_get, name='course-list'),
    path('add/', views.course_add, name='course-add'),
    path('update/<int:course_id>', views.course_update, name='course-update'),
    path('delete/<int:course_id>', views.course_delete, name='course-delete')
]

levels/urls.py
from django.urls import path
from . import views

app_name = 'levels'

urlpatterns = [
    path('get/', views.levels_get, name='level-list'),
    path('get/all/', views.levels_get, name='level-list-all'),
    path('get/<int:class_id>', views.level_details, name='level-details'),
    path('add/', views.level_add, name='level-add'),
    path('update/<int:class_id>', views.level_update, name='level-update'),
    path('delete/<int:class_id>', views.level_delete, name='level-delete')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from levels import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('students/', include('students.urls')),
    path('class/', include('levels.urls')),
    path('course/', include('courses.urls')),

    path('', views.levels_get),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('add/', views.student_add, name='student-add'),
    path('update/<int:student_id>/', views.student_update, name='student-update'),
    path('del/<int:student_id>/<int:class_id>/', views.student_delete, name='student-delete'),
    path('profile/<int:student_id>', views.profile, name='student-profile'),
    path('all/<int:class_id>/<int:course_id>', views.students_get, name='students-list'),
    path('mark/', views.mark_attendance_manually, name="student-attendance-mark"),
    path('mark/auto/', views.mark_attendance_automatically, name="student-attendance-mark-automatically"),

    path('email/', views.email_warning, name="email-service"),
    path('stats/<int:course_id>/<int:class_id>/<int:teacher_id>', views.stats, name='students-stats'),
    path('stats/details/<int:detail_id>', views.stats_details, name="students-stats-details")
]

levels/models.py
from django.db import models
from courses.models import Course


# Create your models here.
class Class_uni(models.Model):
    name = models.CharField(max_length=120)  # max_length = required

    course = models.ManyToManyField(Course)

    def __str__(self):
        return self.name

levels/forms.py
from django.forms import ModelForm
from levels.models import Class_uni
from courses.models import Course
from django import forms


class CreateClassForm(ModelForm):

    name = forms.CharField(label='Name',
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    course = forms.ModelMultipleChoiceField(queryset=Course.objects.all(), required=True, widget=forms.SelectMultiple(attrs={'class': 'form-control c'}))

    class Meta:
        model = Class_uni
        fields = '__all__'

levels/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from authentication.models import UserProfile
from levels.filters import ClassFilter
from levels.forms import CreateClassForm
from levels.models import Class_uni
from students.models import Student


# Create your views here.

@login_required(login_url='teachers:login')
def levels_get(request):
    if request.user.is_staff:
        classes = Class_uni.objects.all()

        my_filter = ClassFilter(request.GET, queryset=classes)
        classes = my_filter.qs

        context = {
            "classes": classes
        }
        return render(request, '../templates/levels_grid_all.html', context)
    else:
        user_profile = UserProfile.objects.get(user_id=request.user.id)
        classe = user_profile.classes.all()

        my_filter = ClassFilter(request.GET, queryset=classe)
        classe = my_filter.qs

        context = {
            "classes": classe
        }
        return render(request, '../templates/levels_grid.html', context)


def levels_get_all(request):
    classes = Class_uni.objects.all()

    my_filter = ClassFilter(request.GET, queryset=classes)
    classes = my_filter.qs

    context = {
        "classes": classes
    }

    return render(request, '../templates/levels_grid_all.html', context)


def level_add(request):
    form = CreateClassForm()
    classe = Class_uni()

    if request.method == 'POST':
        form = CreateClassForm(request.POST, request.FILES, instance=classe)
        if form.is_valid():
            form.save()
            return redirect(reverse('levels:level-list-all'))
    else:
        form = CreateClassForm()

    context = {
        'form': form
    }

    return render(request, '../templates/level_add.html', context)


def level_details(request, class_id):
    classe = Class_uni.objects.get(id=class_id)
    students = Student.objects.filter(class_id=class_id)
    courses = classe.course.all()

    course_id = 0
    context = {
        'class': classe,
        'courses': courses,
        'students': students,
        'courseid': course_id
    }

    return render(request, '../templates/level_details.html', context)


def level_update(request, class_id):
    classe = Class_uni.objects.get(id=class_id)
    form = CreateClassForm(request.POST, request.FILES, instance=classe)

    if request.method == 'POST':
        form = CreateClassForm(request.POST, request.FILES, instance=classe)
        if form.is_valid():
            form.save()
            messages.success(request, 'Student successfully updated')
            return redirect(reverse('students:student-add'))
    else:
        form = CreateClassForm()

    context = {
        'classe': classe,
        'form': form
    }

    return render(request, '../templates/level_add.html', context)


def level_delete(request, class_id):
    classe = Class_uni.objects.get(id=class_id)
    classe.delete()
    messages.success(request, 'Classe successfully deleted')

    return redirect(reverse('levels:level-list-all'))

levels/templates/level_add.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<form method="POST" action="" class="login-form">
    {% csrf_token %}
   {{form.errors}}
    {{form.as_p}}

    <button type="submit"
        class="btn-fill-lmd radius-30 text-light shadow-light-sea-green    bg-light-sea-green">Send</button>
</form>
{% endblock %}

levels/templates/level_details.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="item-title">
    <h3> {{class.name}} </h3>
</div>

<div class="row gutters-20">
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="dashboard-summery-one mg-b-20">
            <div class="row align-items-center">
                <div class="col-6">
                    <div class="item-icon bg-light-green ">
                        <i class="flaticon-classmates text-green"></i>
                    </div>
                </div>
                <div class="col-6">
                    <div class="item-content">
                        <div class="item-title">Students</div>
                        <div class="item-number"><span class="counter">{{students.count}}</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="dashboard-summery-one mg-b-20">
            <div class="row align-items-center">
                <div class="col-6">
                    <div class="item-icon bg-light-blue">
                        <i class="flaticon-multiple-users-silhouette text-blue"></i>
                    </div>
                </div>
                <div class="col-6">
                    <div class="item-content">
                        <div class="item-title">Teachers</div>
                        <div class="item-number"><span class="counter">{{courses.count}}</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="float: right;">
    <form action="{% url 'levels:level-delete' class.id %}" method="post">
        {% csrf_token %}
        <button type="submit"  type="button"
        data-toggle="tooltip" data-placement="top" title="Delete" class="btn radius-30 text-light shadow-red bg-red">Delete</button>
    </form>
    <a href="{% url 'levels:level-update' class_id=class.id %}" type="submit" data-toggle="tooltip" data-placement="top" title="Update" class="btn radius-30 text-light shadow-light-sea-green    bg-light-sea-green">Update</a>
</div>
<div class="table-responsive">
    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">
        <table class="table display data-table text-nowrap dataTable no-footer" id="DataTables_Table_0" role="grid">
            <thead>
                <tr role="row">

                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                        aria-label="Photo: activate to sort column ascending" style="width: 43px;">Photo
                    </th>
                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                        aria-label="Name: activate to sort column ascending" style="width: 82px;">Name
                    </th>
                    <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                        aria-label="Phone: activate to sort column ascending" style="width: 101px;">
                        Phone</th>
                    <th rowspan="1" colspan="1" aria-label="E-mail: activate to sort column ascending"
                        style="width: 168px;">E-mail</th>
                    <th rowspan="1" colspan="1" aria-label="" style="width: 48px;"></th>
                    {% if courseid != 0 %}
                    <th rowspan="1" colspan="1" style="width: 87px;">
                        <div class="form-check">
                            <label class="form-check-label">Présent</label>
                            <input type="checkbox" class="form-check-input checkAll">
                        </div>
                    </th>
                    {% endif %}
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <form action="{% url 'students:student-attendance-mark' %}" method="post">
                    {% csrf_token %}
                    <tr role="row" class="odd">
                        <td class="text-center"><img class="avatar" src="{{student.profile_pic.url}}" alt="student">
                        </td>
                        <td class="text-left"><a href="{% url 'students:student-profile' student_id=student.id %}">
                                {{student.last_name}} {{student.first_name}} </a></td>
                        <td>{{student.phone}}</td>
                        <td>{{student.email}}</td>
                        <td>
                        </td>
                        {% if courseid != 0 %}
                        <td class="sorting_1">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="p" value={{student.id}}>
                                <label class="form-check-label"> </label>
                            </div>
                        </td>
                        {% else %}
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <a href="{% url 'students:student-update' student_id=student.id %}" type="button"
                                data-toggle="tooltip" data-placement="top" title="Update"
                                class="btn radius-30 text-light bg-orange-peel"><i
                                    style="position: relative; left:-20%;" class="fas fa-cog mg-l-10"></i></a>

                            <form action="{% url 'students:student-delete' student_id=student.id class_id=class.id%}"
                                method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn radius-30 text-light bg-red" data-toggle="tooltip"
                                    data-placement="top" title="Delete"><i style="position: relative; left:-20%;"
                                        class="fas fa-exclamation-circle mg-l-10"></i></button>
                            </form>


                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
        {% if courseid != 0 %}
        <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 float-right form-group">
            <input type="hidden" name="course_id" value={{courseid}}>
            <input type="submit" class="fw-btn-fill btn-gradient-yellow" value="Mark P" />
        </div>
        {% endif %}
        </form>
    </div>
</div>

{% endblock %}

levels/templates/levels_grid.html
{% extends "base.html" %}

{% block content %}

<div class="page-body">
      <form class="mg-b-20">
                    <div class="row gutters-8">
                        {{ my_filter.form}}
                        <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
                            <input type="text" name="name"  id="name" placeholder="Class name" class="form-control">
                        </div>
                        <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                            <button type="submit" class="btn btn-success">SEARCH</button> <br>
                            <button onClick="window.location.href=window.location.href" class="btn btn-warning" >Reset</button>
                        </div>
                    </div>
                </form>
    <div class="row">

        {% for class in classes %}
        <div class="col-sm-6 col-md-6 col-lg-3">
            <div class="team-block">
                <a href="{% url 'courses:course-list' class_id=class.id %}" class="btn btn-gradient-yellow" style="    margin: 4% 4% 4% 0;
               height: 75px;
               width: 175px;
               color: white;
               font-style: bolder;
               font-size: 15px;"><span style="position: relative;top: 20px;display: flex;justify-content: center;flex-wrap: wrap;"> {{class.name}} </span></a>
            </div>
        </div>
        {% endfor %}
        <div>
        </div>
        {% endblock %}

levels/templates/levels_grid_all.html
{% extends "base.html" %}

{% block content %}

<div class="page-body">
    <form class="mg-b-20">
                    <div class="row gutters-8">
                        {{ my_filter.form}}
                        <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
                            <input type="text" name="name"  id="name" placeholder="Class name" class="form-control">
                        </div>
                        <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                            <button type="submit" class="btn btn-success">SEARCH</button> <br>
                            <button onClick="window.location.href=window.location.href" class="btn btn-warning" >Reset</button>
                        </div>
                    </div>
                </form>
  <div class="row">
    {% for class in classes %}
    <div class="col-sm-6 col-md-6 col-lg-3">
      <div class="team-block">
        <a href="{% url 'levels:level-details' class_id=class.id %}" class="btn btn-gradient-yellow" style="    margin: 4% 4% 4% 0;
               height: 75px;
               width: 175px;
               color: white;
               font-style: bolder;
               font-size: 15px;"> <span style="position: relative;top: 20px;display: flex;justify-content: center;flex-wrap: wrap;">{{class.name}}</span> </a>
      </div>
    </div>
    {% endfor %}
    <div>
    </div>
    {% endblock %}