courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('get/', views.course_get_all_teacher, name='course-get'),
    path('get/all', views.course_get_all, name='course-get-all'),
    path('get/<int:class_id>', views.course_get, name='course-list'),
    path('add/', views.course_add, name='course-add'),
    path('update/<int:course_id>', views.course_update, name='course-update'),
    path('delete/<int:course_id>', views.course_delete, name='course-delete')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from levels import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('students/', include('students.urls')),
    path('class/', include('levels.urls')),
    path('course/', include('courses.urls')),

    path('', views.levels_get),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('add/', views.student_add, name='student-add'),
    path('update/<int:student_id>/', views.student_update, name='student-update'),
    path('del/<int:student_id>/<int:class_id>/', views.student_delete, name='student-delete'),
    path('profile/<int:student_id>', views.profile, name='student-profile'),
    path('all/<int:class_id>/<int:course_id>', views.students_get, name='students-list'),
    path('mark/', views.mark_attendance_manually, name="student-attendance-mark"),
    path('mark/auto/', views.mark_attendance_automatically, name="student-attendance-mark-automatically"),

    path('email/', views.email_warning, name="email-service"),
    path('stats/<int:course_id>/<int:class_id>/<int:teacher_id>', views.stats, name='students-stats'),
    path('stats/details/<int:detail_id>', views.stats_details, name="students-stats-details")
]

courses/models.py
from django.db import models


# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=120)  # max_length = required
    absences_number = models.IntegerField()

    def __str__(self):
        return self.name

courses/forms.py
from django.forms import ModelForm
from courses.models import Course


class CreateCourseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

courses/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse

from courses.filters import CourseFilter
from courses.forms import CreateCourseForm
from authentication.models import UserProfile
from django.contrib.auth.decorators import login_required

# Create your views here.
from courses.models import Course
from levels.models import Class_uni


@login_required(login_url='login')
def course_get_all_teacher(request):
    user_profile = UserProfile.objects.get(user_id=request.user.id)
    courses = user_profile.courses.all()

    my_filter = CourseFilter(request.GET, queryset=courses)
    courses = my_filter.qs

    context = {
        "courses": courses
    }
    return render(request, '../templates/course_grid.html', context)


@login_required(login_url='login')
def course_get_all(request):
    courses = Course.objects.all()

    my_filter = CourseFilter(request.GET, queryset=courses)
    courses = my_filter.qs

    context = {
        "courses": courses
    }
    return render(request, '../templates/course_grid_all.html', context)


def course_add(request):
    form = CreateCourseForm()
    course = Course()
    if request.method == 'POST':
        form = CreateCourseForm(request.POST, request.FILES, instance=course)
        if form.is_valid():
            form.save()
            return redirect(reverse('courses:course-get-all'))
    else:
        form = CreateCourseForm()

    context = {
        'form': form
    }
    return render(request, '../templates/course_add.html', context)


def course_update(request, course_id):
    course = Course.objects.get(id=course_id)
    form = CreateCourseForm(request.POST, request.FILES, instance=course)

    if request.method == 'POST':
        form = CreateCourseForm(request.POST, request.FILES, instance=course)
        if form.is_valid():
            form.save()
            messages.success(request, 'Course successfully updated')
            return redirect(reverse('courses:course-get-all'))

    is_update = True

    context = {
        'course': course,
        'form': form,
        'is_update': is_update
    }

    return render(request, '../templates/course_add.html', context)


def course_get(request, class_id):
    classe = Class_uni.objects.get(id=class_id)
    courses = classe.course.all()

    context = {
        "courses": courses,
        "classid": class_id
    }
    return render(request, '../templates/course_grid.html', context)


def course_delete(request, course_id):

    course = Course.objects.get(id=course_id)
    course.delete()
    messages.success(request, 'Course successfully deleted')

    return redirect(reverse('courses:course-get-all'))

courses/templates/course_add.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<form method="POST" action="" class="login-form">
    {% csrf_token %}

    <div class="form-group">
        <label>Name</label>
        <input type="text" name="name" class="form-control" value={{course.name}}>
    </div>

    <div class="form-group">
        <label>Number of absences</label>
        <input type="number" name="absences_number" class="form-control" value={{course.absences_number}}>
    </div>
    <br>

    <div class="form-group">
        {% if is_update %}
            <button type="submit" class="btn radius-30 text-light shadow-light-sea-green    bg-light-sea-green">Update</button>
        {% else %}
            <button type="submit"
            class="btn-fill-lmd radius-30 text-light shadow-light-sea-green    bg-light-sea-green">Send</button>
        {% endif %}
    </div>
</form>

    {% if is_update %}

    <form action="{% url 'courses:course-delete' course.id %}" method="post">
        {% csrf_token %}
        <button type="submit" style="position: relative;
        top: -38px;
        left: 6%;" class="btn radius-30 text-light shadow-red bg-red">Delete</button>
    </form>
    {% endif %}

{% endblock %}

courses/templates/course_grid.html
{% extends "base.html" %}

{% block content %}
<div class="page-body">
      <form class="mg-b-20">
                    <div class="row gutters-8">
                        {{ my_filter.form}}
                        <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
                            <input type="text" name="name"  id="name" placeholder="Course name" class="form-control">
                        </div>
                        <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                            <button type="submit" class="btn btn-success">SEARCH</button> <br>
                            <button onClick="window.location.href=window.location.href" class="btn btn-warning" >Reset</button>
                        </div>
                    </div>
                </form>
    <div class="row">
        {% for course in courses %}
        <div class="col-sm-6 col-md-6 col-lg-3">
            <div class="team-block">
                {% if request.user.is_staff %}
               <a href="{% url 'courses:course-update'  course_id=course.id %}" class="btn btn-gradient-yellow" style="    margin: 4% 4% 4% 0;
               height: 75px;
               width: 175px;
               color: white;
               font-style: bolder;
               font-size: 15px;"> {{course.name}} </a>
                    {% else %}


                 <a href="{% url 'students:students-list' class_id=classid course_id=course.id%}" class="btn btn-gradient-yellow" style="    margin: 4% 4% 4% 0;
               height: 75px;
               width: 175px;
               color: white;
               font-style: bolder;
               font-size: 15px;"><span style="position: relative;top: 20px;display: flex;justify-content: center;flex-wrap: wrap;"> {{course.name}} </span> </a>
   {% endif %}
            </div>
        </div>
        {% endfor %}
</div>
{% endblock %}

courses/templates/course_grid_all.html
{% extends "base.html" %}

{% block content %}
<div class="page-body">

  <form class="mg-b-20">
                    <div class="row gutters-8">
                        {{ my_filter.form}}
                        <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
                            <input type="text" name="name"  id="name" placeholder="Course name" class="form-control">
                        </div>
                        <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
                            <button type="submit" class="btn btn-success">SEARCH</button> <br>
                            <button onClick="window.location.href=window.location.href" class="btn btn-warning" >Reset</button>
                        </div>
                    </div>
                </form>
    <div class="row">
        {% for course in courses %}
        <div class="col-sm-6 col-md-6 col-lg-3">
            <div class="team-block">
               <a href="{% url 'courses:course-update' course_id=course.id %}" class="btn btn-gradient-yellow" style="    margin: 4% 4% 4% 0;
               height: 75px;
               width: 175px;
               color: white;
               font-style: bolder;
               font-size: 15px;"> <span style="position: relative;top: 20px;display: flex;justify-content: center;flex-wrap: wrap;">{{course.name}} </span> </a>
            </div>
        </div>
        {% endfor %}
</div>
{% endblock %}