authentication/urls.py
from django.urls import path

from .views import (home, registerPage, loginPage, logoutUser, profile, teachers_get,createTeacherProfile, profile_update, teacher_delete)

app_name = "teachers"

urlpatterns = [
    path('', home, name="home"),
    path('all/', teachers_get, name='teachers-list'),
    path('profile/<int:teacher_id>', profile, name='profile'),

    path('update/<int:teacher_id>/', profile_update, name='teacher-update'),
    path('del/<int:teacher_id>/', teacher_delete, name='teacher-delete'),

    path('register/', registerPage, name="register"),
    path('create/teacher/', createTeacherProfile, name="create-profile"),

    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout")
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('get/', views.course_get_all_teacher, name='course-get'),
    path('get/all', views.course_get_all, name='course-get-all'),
    path('get/<int:class_id>', views.course_get, name='course-list'),
    path('add/', views.course_add, name='course-add'),
    path('update/<int:course_id>', views.course_update, name='course-update'),
    path('delete/<int:course_id>', views.course_delete, name='course-delete')
]

levels/urls.py
from django.urls import path
from . import views

app_name = 'levels'

urlpatterns = [
    path('get/', views.levels_get, name='level-list'),
    path('get/all/', views.levels_get, name='level-list-all'),
    path('get/<int:class_id>', views.level_details, name='level-details'),
    path('add/', views.level_add, name='level-add'),
    path('update/<int:class_id>', views.level_update, name='level-update'),
    path('delete/<int:class_id>', views.level_delete, name='level-delete')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from levels import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('students/', include('students.urls')),
    path('class/', include('levels.urls')),
    path('course/', include('courses.urls')),

    path('', views.levels_get),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('add/', views.student_add, name='student-add'),
    path('update/<int:student_id>/', views.student_update, name='student-update'),
    path('del/<int:student_id>/<int:class_id>/', views.student_delete, name='student-delete'),
    path('profile/<int:student_id>', views.profile, name='student-profile'),
    path('all/<int:class_id>/<int:course_id>', views.students_get, name='students-list'),
    path('mark/', views.mark_attendance_manually, name="student-attendance-mark"),
    path('mark/auto/', views.mark_attendance_automatically, name="student-attendance-mark-automatically"),

    path('email/', views.email_warning, name="email-service"),
    path('stats/<int:course_id>/<int:class_id>/<int:teacher_id>', views.stats, name='students-stats'),
    path('stats/details/<int:detail_id>', views.stats_details, name="students-stats-details")
]

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Markini | {% block title %}{% endblock %} </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/img/favicon.png' %}">
    <!-- Normalize CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
    <!-- Main CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
    <!-- Flaticon CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/flaticon.css' %}">
    <!-- Animate CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- Modernize js -->
    <script src="{% static 'js/modernizr-3.6.0.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js"></script>

    <style>
       input[type=text],input[type=email],input[type=phone],input[type=file],input[type=password],  input[type=number], .date, .c, #id_classe {
          width: 100%;
          height:50px;
          font-size:15px;
          padding: 12px 20px;
          margin: 8px 0;
          box-sizing: border-box;
        }
    </style>

</head>

<body>

    <!-- Preloader Start Here -->
    <!-- Preloader End Here -->
    <div id="wrapper" class="wrapper bg-ash">
        <!-- Header Menu Area Start Here -->
        <div class="navbar navbar-expand-md header-menu-one bg-light">
            <div class="nav-bar-header-one">
                <div class="header-logo">
                    <a href="index.html">
                        <img src="{% static 'images/img/210x50.png' %}" alt="logo" style="position:relative;left:-17%;">
                    </a>
                </div>
                <div class="toggle-button sidebar-toggle">
                    <button type="button" class="item-link">
                        <span class="btn-icon-wrap">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="d-md-none mobile-nav-bar">
                <button class="navbar-toggler pulse-animation" type="button" data-toggle="collapse"
                    data-target="#mobile-navbar" aria-expanded="false">
                    <i class="far fa-arrow-alt-circle-down"></i>
                </button>
                <button type="button" class="navbar-toggler sidebar-toggle-mobile">
                    <i class="fas fa-bars"></i>
                </button>
            </div>
            <div class="header-main-menu collapse navbar-collapse" id="mobile-navbar">
                <ul class="navbar-nav">

                </ul>
                <ul class="navbar-nav">
                    <li class="navbar-item dropdown header-admin">
                        <a class="navbar-nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                            aria-expanded="false">
                            <div class="admin-title">
                                <h5 class="item-title">Hello, {{ request.user }} </h5>
                            </div>
                            <div class="admin-img">
                                <img src="{% static 'images/img/figure/admin.jpg' %}" alt="Admin">
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <div class="item-header">
                                <h6 class="item-title">{{ request.user }}</h6>
                            </div>
                            <div class="item-content">
                                <ul class="settings-list">
                                    <li><a href="{% url 'teachers:logout' %}"><i class="flaticon-turn-off"></i>Log
                                            Out</a></li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Header Menu Area End Here -->
        <!-- Page Area Start Here -->
        <div class="dashboard-page-one">
            <!-- Sidebar Area Start Here -->
            <div class="sidebar-main sidebar-menu-one sidebar-expand-md sidebar-color">
                <div class="mobile-sidebar-header d-md-none">
                    <div class="header-logo">
                        <a href="index.html"><img src="img/logo1.png" alt="logo"></a>
                    </div>
                </div>
                <div class="sidebar-menu-content">
                    <ul class="nav nav-sidebar-menu sidebar-toggle-view">

                        {% if request.user.is_staff %}
                        <li class="nav-item sidebar-nav-item">
                            <a href="#" class="nav-link"><i class="flaticon-classmates"></i><span>Students</span></a>
                            <ul class="nav sub-group-menu">
                                <li class="nav-item">
                                    <a href="{% url 'levels:level-list-all' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>All students</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'students:student-add' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>Add student</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item sidebar-nav-item">
                            <a href="#" class="nav-link"><i class="flaticon-classmates"></i><span>Teachers</span></a>
                            <ul class="nav sub-group-menu ">
                                <li class="nav-item">
                                    <a href="{% url 'teachers:teachers-list' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>All teachers</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'teachers:register' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>Add teacher</a>
                                </li>
                            </ul>
                        </li>
                        {% endif %}
                        <li class="nav-item sidebar-nav-item">
                            <a href="#" class="nav-link"><i class="flaticon-classmates"></i><span>Classes</span></a>
                            <ul class="nav sub-group-menu ">

                                {% if request.user.is_staff %}
                                 <li class="nav-item">
                                    <a href="{% url 'levels:level-list-all' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>All classes</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'levels:level-add' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>Add class</a>
                                </li>
                                   {% else %}
                                <li class="nav-item">
                                    <a href="{% url 'levels:level-list' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>My classes</a>
                                </li>
                                {% endif %}
                            </ul>
                        </li>

                        <li class="nav-item sidebar-nav-item">
                            <a href="#" class="nav-link"><i class="flaticon-classmates"></i><span>Courses</span></a>
                            <ul class="nav sub-group-menu ">

                                {% if request.user.is_staff %}
                                <li class="nav-item">
                                    <a href="{% url 'courses:course-get-all' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>All courses</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'courses:course-add' %}" class="nav-link"><i
                                            class="fas fa-angle-right"></i>Add course</a>
                                </li>
                                {% endif %}
                            </ul>
                        </li>

                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>
                        <li class="nav-item sidebar-nav-item"> &nbsp </li>

                    </ul>
                </div>
            </div>
            <!-- Sidebar Area End Here -->
            <div class="dashboard-content-one">
                <!-- Breadcubs Area Start Here -->
                <div class="breadcrumbs-area">
                    <h3></h3>
                    <ul>
                        <li>
                            <a href="index.html">Home</a>
                        </li>
                        <li></li>
                    </ul>
                </div>
                <!-- Breadcubs Area End Here -->
                <!-- Student Details Area Start Here -->
                <div class="card height-auto">
                    <div class="card-body">
                        <div class="heading-layout1">
                            <div class="item-title">
                                <h3></h3>
                            </div>
                        </div>

                     	{% for message in messages %}
                            <div class="alert alert-info" role="alert">
                                <p id="messages">{{message}}</p>
                            </div>
                        {% endfor %}

                        {% block content %}{% endblock %}
                    </div>
                </div>
                <!-- Student Details Area End Here -->
                <footer class="footer-wrap-layout1">
                    <div class="copyright">© Copyrights <a href="#">Markini</a> 2020. All rights reserved. </div>
                </footer>
            </div>
        </div>
        <!-- Page Area End Here -->
    </div>
    <!-- jquery-->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Scroll Up Js -->
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <!-- Counterup Js -->
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <!-- Chart Js -->
    <script src="{% static 'js/Chart.min.js' %}"></script>
    <!-- Custom Js -->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>